name: Build & Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  DOCKER_USER: ${{ vars.DOCKER_USER }}

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          mkdir -p artifacts
          docker save ${{ env.IMAGE_NAME }}:${{ github.ref_name }} > artifacts/docker-image.tar

      - name: Save Image
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: artifacts
          retention-days: 1

  push_image:
    needs: build_image
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Docker Image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: artifacts

      - name: Load Image
        run: |
          cd artifacts
          docker load < docker-image.tar

      - name: Login
        run: |
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ env.DOCKER_USER }} --password-stdin

      - name: Push Image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ github.ref_name }} ghcr.io/blackbadpinguin/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker push ghcr.io/blackbadpinguin/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker tag ghcr.io/blackbadpinguin/${{ env.IMAGE_NAME }}:${{ github.ref_name }} ghcr.io/blackbadpinguin/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/blackbadpinguin/${{ env.IMAGE_NAME }}:latest

  trigger_deployment:
    needs: push_image
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: trigger_deployment

  cleanup:
    needs: push_image
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docker-artifact
